owner: kizzna
repo: bovorn-mon

sites:
    - name: MON-8-11
      url: $MON_URL/e49a427f546380a2.html
    - name: MON-8-12
      url: $MON_URL/14ce129a02693bd2.html
    - name: MON-8-13
      url: $MON_URL/b42895fc15b15291.html
    - name: MON-8-14
      url: $MON_URL/b576b6317fe00336.html
    - name: MON-9-1
      url: $MON_URL/dc10904dcec48a04.html
    - name: MON-9-2
      url: $MON_URL/541fec86a12fda74.html
    - name: MON-9-3
      url: $MON_URL/c5838d617ce030ec.html
    - name: MON-9-4
      url: $MON_URL/8d4c4866c8d5943c.html
    - name: MON-9-5
      url: $MON_URL/b4d446e2c959989a.html
    - name: MON-9-6
      url: $MON_URL/bf7ee37fa62dd1ac.html
    - name: MON-9-7
      url: $MON_URL/92d3bd2eab1a6610.html
    - name: MON-9-8
      url: $MON_URL/7fc694af60404a0c.html
    - name: MON-9-9
      url: $MON_URL/180eb810c6f94002.html
    - name: MON-9-10
      url: $MON_URL/96d74883e62fb2eb.html
    - name: MON-9-11
      url: $MON_URL/cac5c4e6940b61c6.html
    - name: MON-9-12
      url: $MON_URL/92a47a4a42be0122.html
    - name: MON-9-13
      url: $MON_URL/75af5cbfcf345397.html
    - name: MON-9-14
      url: $MON_URL/2e12a21b9e0e8a25.html
    - name: MON-9-15
      url: $MON_URL/860c0b2a15340129.html
    - name: MON-9-16
      url: $MON_URL/4d1305259ab37be7.html
    - name: MON-9-17
      url: $MON_URL/68db9e6994aceb66.html
    - name: MON-9-18
      url: $MON_URL/bc830a996f39b78e.html
    - name: MON-9-19
      url: $MON_URL/2a72df0189a968e1.html
    - name: MON-9-20
      url: $MON_URL/4c9ac5e894ed26d1.html
    - name: MON-9-21
      url: $MON_URL/ca4e8d48d400e1a2.html
    - name: MON-9-22
      url: $MON_URL/0a7ac8614b2057a9.html
    - name: MON-9-23
      url: $MON_URL/4b76e69bb1f584ce.html
    - name: MON-9-24
      url: $MON_URL/e38a6786382f6845.html
    - name: MON-9-25
      url: $MON_URL/6a6494fa7526e54a.html
    - name: MON-9-26
      url: $MON_URL/0cbe7988a11e6ee5.html
    - name: MON-9-27
      url: $MON_URL/ec0f87db5188d7f9.html
    - name: MON-9-28
      url: $MON_URL/928961811579f782.html
    - name: MON-9-29
      url: $MON_URL/8fddd092e57ab38b.html
    - name: MON-9-30
      url: $MON_URL/52299095291ebf50.html
    - name: MON-9-31
      url: $MON_URL/9f42003cea7ff834.html
    - name: MON-9-32
      url: $MON_URL/29622587fc2114aa.html
    - name: MON-9-33
      url: $MON_URL/b434db2e8c65b249.html
    - name: MON-9-34
      url: $MON_URL/1ce21cc34f1cc857.html
    - name: MON-9-35
      url: $MON_URL/7d2b039ae4d622c3.html
    - name: MON-9-36
      url: $MON_URL/a419ade7aaf7ae8a.html
    - name: MON-9-37
      url: $MON_URL/03282c2f81be3aa1.html
    - name: MON-9-38
      url: $MON_URL/a4717ddf063c2c51.html
    - name: MON-9-39
      url: $MON_URL/344b543f08e97180.html
    - name: MON-9-40
      url: $MON_URL/b7e776fe39c46719.html
    - name: MON-9-41
      url: $MON_URL/b5b22be74445ba5e.html
    - name: MON-9-42
      url: $MON_URL/bf390f3295269e73.html
    - name: MON-9-43
      url: $MON_URL/4371bec20df801b3.html
    - name: MON-9-44
      url: $MON_URL/5857298b341d4c64.html
    - name: MON-9-45
      url: $MON_URL/0eaebd2022908fcc.html
    - name: MON-9-46
      url: $MON_URL/8af2746a5ab5b85c.html
    - name: MON-9-47
      url: $MON_URL/c161533fd24f9c2c.html
    - name: MON-9-48
      url: $MON_URL/343a8bdf913f4af1.html
    - name: MON-9-49
      url: $MON_URL/464aba5df58c0cc0.html
    - name: MON-9-50
      url: $MON_URL/dda74b660a11199d.html
    - name: MON-9-51
      url: $MON_URL/b509792c5b60e21d.html
    - name: MON-9-52
      url: $MON_URL/45e35947a8a02a20.html
    - name: MON-9-53
      url: $MON_URL/4a6d5e430e7de861.html
    - name: MON-9-54
      url: $MON_URL/3c93f8a41fd1126b.html
    - name: MON-9-55
      url: $MON_URL/477049b9e67b56ca.html
    - name: MON-9-56
      url: $MON_URL/881ee43f1d55ec5e.html
    - name: MON-9-57
      url: $MON_URL/9ee81f0683173b4b.html
    - name: MON-9-58
      url: $MON_URL/613bcc19afd97be7.html
    - name: MON-9-59
      url: $MON_URL/f2fd8f9b0ea36669.html
    - name: MON-9-60
      url: $MON_URL/1c3bc42a9fb892f1.html
    - name: MON-9-61
      url: $MON_URL/99440d05754e82b2.html
    - name: MON-9-62
      url: $MON_URL/8be0c2d1e13c9452.html
    - name: MON-9-63
      url: $MON_URL/e2da4b85af22b845.html
    - name: MON-9-64
      url: $MON_URL/3768aab6267fbb51.html
    - name: MON-9-65
      url: $MON_URL/f4ba9735884a9c6c.html
    - name: MON-9-66
      url: $MON_URL/5e636df0bb652ecb.html
    - name: MON-9-67
      url: $MON_URL/ee2f9d017bcdd9ec.html
    - name: MON-9-68
      url: $MON_URL/27885ed714cdef67.html
    - name: MON-9-69
      url: $MON_URL/6af1c5edfd17ce5f.html
    - name: MON-9-70
      url: $MON_URL/018841e8af7a8578.html
    - name: MON-9-71
      url: $MON_URL/d4571b53eb3a7c41.html
    - name: MON-9-72
      url: $MON_URL/1b05d6400b0e6889.html
    - name: MON-9-73
      url: $MON_URL/51fff62ad653bb6c.html
    - name: MON-9-74
      url: $MON_URL/fcc684322dcee05d.html
    - name: MON-9-75
      url: $MON_URL/103e18ece3e556df.html
    - name: MON-9-76
      url: $MON_URL/97110aa8029c1c61.html
    - name: MON-9-77
      url: $MON_URL/d21be817e85f04fd.html
    - name: MON-9-78
      url: $MON_URL/a061f46982468525.html
    - name: MON-9-79
      url: $MON_URL/8f27350f1e4a08bf.html
    - name: MON-9-80
      url: $MON_URL/15d1d09e1f891a08.html


status-website:
    # Add your custom domain name, or remove the `cname` line if you don't have a domain
    # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
    baseUrl: /bovorn-mon
    publish: true
    logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
    name: Bovorn-mon
    introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
    introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
    navbar:
        - title: Status
          href: /
        - title: GitHub
          href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
