owner: kizzna
repo: bovorn-mon

sites:
    - name: MON 1
      url: $MON_URL/10_0_9_1.html
    - name: MON 2
      url: $MON_URL/10_0_9_2.html
    - name: MON 3
      url: $MON_URL/10_0_9_3.html
    - name: MON 4
      url: $MON_URL/10_0_9_4.html
    - name: MON 5
      url: $MON_URL/10_0_9_5.html
    - name: MON 6
      url: $MON_URL/10_0_9_6.html
    - name: MON 7
      url: $MON_URL/10_0_9_7.html
    - name: MON 8
      url: $MON_URL/10_0_9_8.html
    - name: MON 9
      url: $MON_URL/10_0_9_9.html
    - name: MON 10
      url: $MON_URL/10_0_9_10.html
    - name: MON 11
      url: $MON_URL/10_0_9_11.html
    - name: MON 12
      url: $MON_URL/10_0_9_12.html
    - name: MON 13
      url: $MON_URL/10_0_9_13.html
    - name: MON 14
      url: $MON_URL/10_0_9_14.html
    - name: MON 15
      url: $MON_URL/10_0_9_15.html
    - name: MON 16
      url: $MON_URL/10_0_9_16.html
    - name: MON 17
      url: $MON_URL/10_0_9_17.html
    - name: MON 18
      url: $MON_URL/10_0_9_18.html
    - name: MON 19
      url: $MON_URL/10_0_9_19.html
    - name: MON 20
      url: $MON_URL/10_0_9_20.html

status-website:
    # Add your custom domain name, or remove the `cname` line if you don't have a domain
    # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
    baseUrl: /bovorn-mon
    publish: true
    logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
    name: Bovorn-mon
    introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
    introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
    navbar:
        - title: Status
          href: /
        - title: GitHub
          href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
